# puts "${Blue}                         dSSSSSSSSSSSSSSSSSSSSSSb                                 "
# puts "${Blue}                       -dSSSSSSSSSSSSSSSSSSSSSSSSb                                "
# puts "${Blue}                       dSSSSSSSSSSS^SSSSSSSSSSSSSSb                               "
# puts "${Blue}                      dSSSSSSSSSSP'  '^TSSSSSSSSSSS;                              "
# puts "${Blue}                     :SSSSSSSSSSP       TSSSSSSSSSSS\                             "
# puts "${Blue}                     :SSSSSSSSSS         TSSSSSSSSSS \                            "
# puts "${Blue}                     SSSSSSSSSS;          SSSSSSSSSS  ;                           "
# puts "${Blue}                     SSSSSSSSSS_.      _._:SSSSSSSSS; :                           "
# puts "${Blue}                    :SSSSSSSSS;--'.   / ---SSSSSSSSSS ;                           "
# puts "${Blue}                    SSSSSSSSSS(@)\     /(@):SSSSSSSSSS                            "
# puts "${Blue}                   :SSSSSSSSS;             :SSSSSSSSSSb.                          "
# puts "${Blue}                   SSSSSSSSSS;             :SSSSSSSSSSTSb                         "
# puts "${Blue}                  :SSSSSSSSSS;             :SSSSSSSSSS SS;                        "
# puts "${Blue}                 dSSSSSSSSSSS;      '      :SSSSSSSSSS :SS                        "
# puts "${Blue}                :SSSSSSSSSSSSS    .---.    SSSSSSSSSSS SS;\                       "
# puts "${Blue}                 TSSSSSSSSSSSs;   '---'   :SSSSSSSSSSSdSP  '-                     "
# puts "${Blue}                  :SSSSSSSSsSSS'.   -   .'SSSSSSSSSSSSP'                          "
# puts "${Blue}                 -'TSSSSSSSSSSSb '.___.' dSSSSSSSSSSSP-                           "
# puts "${Blue}                   /'TSSSSSSSSSS;       :SSSSSSSSSSS(                             "
# puts "${Blue}                 -'.-')^TSSSSP^'         '^TSSSSP^''-'-._                         "
# puts "${Blue}              .--''''---...             ___...---'''   dSj'--.                    "
# puts "${Blue}           .-'                      --'               dSP     \                   "
# puts "${Blue}          /           ██████╗  █████╗ ██████╗        dSP       ;                  "
# puts "${Blue}         :           ██╔════╝ ██╔══██╗██╔══██╗      :SS        :                  "
# puts "${Blue}         ;           ██║  ███╗███████║██████╔╝      SS;        :                  "
# puts "${Blue}         ;           ██║   ██║██╔══██║██╔═══╝      :SS         :                  "
# puts "${Blue}         ;        ;  ╚██████╔╝██║  ██║██║          SS;         ;                  "
# puts "${Blue}         ;        ::  ╚═════╝ ╚═╝  ╚═╝╚═╝         :SS         :                   "
# puts "${Blue}         :         ;                ;             SS;         :                   "
# puts "${Blue}          ;      ._L_               : ____....ssssSSSb        :                   "
# puts "${Blue}          ;    .dsPsSSSss..__...sssSSSSSSSSSSSSSSSSSSS;       :                   "
# puts "${Blue}          ;   dsPjSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS       ;                   "
# puts "${Blue}          :  dsP sSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS;      ;                   "
# puts "${Blue}          : dsP :sSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSs      ;                   "
# puts "${Blue}          :dsP  SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSs     :                    "
# puts "${Blue}          dsP   SSSSSSS  SSSSSSSSSSSSSSSSSSSSS  SSSSSSSs     :                    "
# puts "${Blue}         dsP    :sSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSs;     :                    "
# puts "${Blue}         TP;     SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS      ;                    "
# puts "${NC}"
#                                                                        "
puts "${Blue}                          ______                                  "
puts "${Blue}                     . '''  :.  ''' .                             "
puts "${Blue}                 ..'. . . . : . . . . ` .                         "
puts "${Blue}               .':.,.... .  :  ...,.... .`                        "
puts "${Blue}             .'::...,., .   ; .  . .... . .`.                     "
puts "${Blue}           .'::.........  .' `.. . .:.,...., `.                   "
puts "${Blue}          .::::..  .   . '     `...:::;:...... .                  "
puts "${Blue}         .::;:.... . .            `.::::;:::.....                 "
puts "${Blue}         .::;:. . .'                 `.:;:::.....                 "
puts "${Blue}         .::;:...'                      `:::.....                 "
puts "${Blue}         .::;:.'                          `:.....                 "
puts "${Blue}         ::.,.                              :....                 "
puts "${Blue}         .... .mMMMMMMmn..       .nmMMMMMMm. :...                 "
puts "${Blue}         .,..     ,,,,  ''`.    ''  ,,,,      :..                 "
puts "${Blue}         .... `.,' (O)`. ,  .  .  .' (O)`,. ' :..                 "
puts "${Blue}         ...,   `.,,,,.'    :     `.,,,,.'    ;.,                 "
puts "${Blue}         ....        . '    ,     ` .         ...                 "
puts "${Blue}         .,..      '                 '       ....                 "
puts "${Blue}         ....              '                  .,.                 "
puts "${Blue}         ..,.             /    '.             ...                 "
puts "${Blue}         ....          , ( _   _ ) .          ...                 "
puts "${Blue}         ....        .    ' `' ''    .        ...                 "
puts "${Blue}         ....     '         '.`          `    .:.                 "
puts "${Blue}         ..,.:.        ._.-''-'`-._.        .;...                 "
puts "${Blue}         ....::.        `-..___..-'        .:...,                 "
puts "${Blue}         ....;:.:.                       .;;;.,..                 "
puts "${Blue}         ..,.:::: `-.       -=-       .-':;:.....                 "
puts "${Blue}         ....:;::    `-._         _.-'   :::.,...                 "
puts "${Blue}         ..,.::::        `-.___.-'       ::.....,                 "
puts "${Blue}         ....::;;                        :::...,.                 "
puts "${Blue}         ...,:::;                        :;:.....                 "
puts "${Blue}_________,...::'                          `::...:________ Kobra   "
puts "${NC}"